# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    - name: Verify Go version
      run: go version # Verify the Go installation and version.
    - name: Run go mod Tidy
      run: go mod tidy

    - name: Check the directory of the project
      run: pwd
    - name: Build
      run: go build -o bin/server.exe server/main.go

    - name: Test
      run: go test -v ./...
