# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    - name: Verify Go version
      run: go version # Verify the Go installation and version.
    - name: Install protoc
      run: |
        sudo apt-get update -y
        sudo apt-get install -y protobuf-compiler

    - name: Set Path of the protoc compiler
      run: export PATH=$PATH:$GOPATH/bin
    - name: Install Protobuf Go Plugin
      run: |
        go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28

    - name: Install gRPC Go Plugin 
      run: |
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2
    - name: Generate gRPC code of the echo.proto file 
      run: |
        protoc --go_out=./Echo --go_opt=paths=source_relative --go-grpc_out=./Echo --go-grpc_opt=paths=source_relative Echo/echo.proto


    - name: Check the directory of the project
      run: pwd
    - name: Bug
      run: go bug
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
